<?xml version="1.0"?>
<!DOCTYPE verbnetRoles-framenetFEs_RoleMappingData  [
  <!ELEMENT verbnetRoles-framenetFEs_RoleMappingData (vncls+)>
  <!ELEMENT vncls   (roles)>
  <!ELEMENT roles   (role+)>
  <!ELEMENT role   (#PCDATA)>
  <!ATTLIST verbnetRoles-framenetFEs_RoleMappingData date CDATA #IMPLIED>
  <!ATTLIST vncls class   CDATA #REQUIRED>
  <!ATTLIST vncls fnframe CDATA #REQUIRED>
  <!ATTLIST role  fnrole  CDATA #REQUIRED>
  <!ATTLIST role  vnrole  CDATA #REQUIRED>
]>

<!-- last updated by Russell on 2010.03.08 -->

<verbnetRoles-framenetFEs_RoleMappingData  date='8-28-06'>
  <vncls class='9.1' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.1-1' fnframe='Installing'> <!-- added for 'install' -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Fixed_location' vnrole='Destination'/>
      <role fnrole='Component' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.2' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.3' fnframe='Cause_impact'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Impactor' vnrole='Theme'/>
      <role fnrole='Impactee' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='9.3' fnframe='Cause_motion'> <!-- added -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='9.3' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Cause' vnrole='Cause'/>
    </roles>
  </vncls>
  <vncls class='9.3' fnframe='Motion_noise'> <!-- added -->
    <roles>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.5' fnframe='Fluidic_motion'>
    <roles>
      <role fnrole='Fluid' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Location'/>
      <role fnrole='Area' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Cause_to_move_in_place'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Body_part' vnrole='Theme'/>
      <role fnrole='Fixed_location' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Reshaping'>
    <roles>
      <role fnrole='Deformer' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Undergoer' vnrole='Theme'/>
      <role fnrole='Body_part' vnrole='Theme'/>
      <role fnrole='Resistant_surface' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Moving_in_place'>
    <roles>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Fixed_location' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Manipulate_into_shape'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Location' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Go_into_shape'>
    <roles>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Place' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.6' fnframe='Body_movement'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Body_part' vnrole='Theme'/>
      <role fnrole='Location' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='9.7' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.7' fnframe='Storing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.7' fnframe='Attaching'> <!-- added; unclear -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Item' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.7' fnframe='Filling'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.7' fnframe='Fluidic_motion'> <!-- added; unclear; only for intransitive frames in the vn class -->
    <roles>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Fluid' vnrole='Theme'/>
    </roles>
 </vncls>
 <vncls class='9.7' fnframe='Mass_motion'> <!-- added; unclear; only for intransitive frames in the vn class -->
    <roles>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Mass_theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.8' fnframe='Adorning'>
    <roles>
      <role fnrole='Location' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.8' fnframe='Filling'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.8' fnframe='Eclipse'>
    <roles>
      <role fnrole='Obstruction' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Eclipsed'/>
    </roles>
  </vncls>
  <vncls class='9.8' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.9' fnframe='Adorning'>
    <roles>
      <role fnrole='Location' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.9' fnframe='Filling'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.9' fnframe='Board_vehicle'>
    <roles>
      <role fnrole='Traveller' vnrole='Agent'/>
      <role fnrole='Vehicle' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='9.9' fnframe='Fining'>
    <roles>
      <role fnrole='Speaker' vnrole='Agent'/>
      <role fnrole='Payer' vnrole='Destination'/>
      <role fnrole='Fine' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.9' fnframe='Preserving'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Medium' vnrole='Destination'/>
      <role fnrole='Undergoer' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.10' fnframe='Placing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Location'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.10' fnframe='Preserving'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Medium' vnrole='Location'/>
      <role fnrole='Undergoer' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.10' fnframe='Inhibit_movement'> <!--  frame name change; Cause_confinement became Inhibit_movement -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goal' vnrole='Location'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.10' fnframe='Provide_lodging'> <!-- added for Provide_lodging.house.v -->
    <roles>
      <role fnrole='Host' vnrole='Agent'/>
      <role fnrole='Residence' vnrole='Location'/>
      <role fnrole='Lodger' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='9.10' fnframe='Imprisonment'> <!-- added for Imprisonment.jail.v -->
    <roles>
      <role fnrole='Authorities' vnrole='Agent'/>
      <role fnrole='Prison' vnrole='Location'/>
      <role fnrole='Prisoner' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='10.1' fnframe='Change_of_leadership'>
    <roles>
      <role fnrole='Selector' vnrole='Agent'/>
      <role fnrole='Old_leader' vnrole='Theme'/>
      <role fnrole='Old_order' vnrole='Theme'/>
      <role fnrole='Role' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.1' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.1' fnframe='Separating'> <!-- not mapping FN roles Whole and Parts b/c the VN class does not include this valence -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Part_1' vnrole='Theme'/>
      <role fnrole='Part_2' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.1' fnframe='Theft'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Victim' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.1' fnframe='Exclude_member'> <!-- added for Exclude_member.excommunicate.v -->
    <roles>
      <role fnrole='Authority' vnrole='Agent'/>
      <role fnrole='Member' vnrole='Theme'/>
      <role fnrole='Group' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.2' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='10.2' fnframe='Extradition'> <!-- created for Extradition.extradite.v -->
    <roles>
      <role fnrole='Authorities' vnrole='Agent'/>
      <role fnrole='Suspect' vnrole='Theme'/>
      <role fnrole='Current_jurisdiction' vnrole='Source'/>
      <role fnrole='Crime_jurisdiction' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='10.3' fnframe='Emptying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.3' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.4.1' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.4.1' fnframe='Manipulation'> <!-- added -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Entity' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Beneficiary'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Taking'> <!-- added -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Kidnapping'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Victim' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Piracy'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Vehicle' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Smuggling'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Beneficiary'/>
    </roles>
  </vncls>
  <vncls class='10.5' fnframe='Theft'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Victim' vnrole='Source'/>
      <role fnrole='Purpose' vnrole='Beneficiary'/>
      <role fnrole='Reason' vnrole='Beneficiary'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Cure'>
    <roles>
      <role fnrole='Healer' vnrole='Agent'/>
      <role fnrole='Affliction' vnrole='Theme'/>
      <role fnrole='Body_part' vnrole='Theme'/>
      <role fnrole='Patient' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Emptying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Robbery'>
    <roles>
      <role fnrole='Perpetrator' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Victim' vnrole='Source'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Verdict'> <!-- added -->
    <roles>
      <role fnrole='Judge' vnrole='Agent'/>
      <role fnrole='Charges' vnrole='Theme'/>
      <role fnrole='Defendant' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Pardon'> <!-- added -->
    <roles>
      <role fnrole='Authority' vnrole='Agent'/>
      <role fnrole='Offense' vnrole='Theme'/>
      <role fnrole='Offender' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.6' fnframe='Manipulate_into_doing'> <!-- added -->
    <roles>
      <role fnrole='Manipulator' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Victim' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.7' fnframe='Emptying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.8' fnframe='Emptying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.10' fnframe='Firing'>
    <roles>
      <role fnrole='Employer' vnrole='Agent'/>
      <role fnrole='Position' vnrole='Predicate'/>
      <role fnrole='Employee' vnrole='Theme'/>
      <role fnrole='Task' vnrole='Source'/> <!-- add correct FE to the frame -->
    </roles>
  </vncls>
  <vncls class='10.10' fnframe='Change_of_leadership'>
    <roles>
      <role fnrole='Selector' vnrole='Agent'/>
      <role fnrole='Role' vnrole='Predicate'/>
      <role fnrole='Old_leader' vnrole='Theme'/>
      <role fnrole='Body' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.10' fnframe='Exclude_member'>
    <roles>
      <role fnrole='Authority' vnrole='Agent'/> <!-- add FE for vn role Predicate (e.g., Role) -->
      <role fnrole='Member' vnrole='Theme'/>
      <role fnrole='Group' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='10.11' fnframe='Quitting'>
    <roles>
      <role fnrole='Employee' vnrole='Agent'/>
      <role fnrole='Position' vnrole='Source'/>
      <role fnrole='Employer' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='11.1' fnframe='Carrying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Carrier' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Path_start' vnrole='Source'/>
      <role fnrole='Path_end' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.1' fnframe='Sending'>
    <roles>
      <role fnrole='Sender' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Recipient' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.1' fnframe='Giving'> <!-- add FE for Source -->
    <roles>
      <role fnrole='Donor' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.1' fnframe='Delivery'> <!-- added for Delivery.deliver.v -->
    <roles>
      <role fnrole='Deliverer' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Goal' vnrole='Destination'/>
      <role fnrole='Recipient' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.1' fnframe='Transfer'> <!-- added for Transfer.transfer.v; FN frame has words that take recipients, but VN class includes both recipients and destinations as "destination" -->
    <roles>
      <role fnrole='Donor' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Destination'/> <!-- what do we do for FE Transferors (and in general P-1 P-2 P-s paradigms? -->
    </roles>
  </vncls>
  <vncls class='11.2' fnframe='Motion'> <!-- added -->
    <roles>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.2' fnframe='Cause_motion'> <!-- added -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.3' fnframe='Carrying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Carrier' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Path_start' vnrole='Source'/>
      <role fnrole='Path_end' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.4' fnframe='Carrying'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Carrier' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Path_start' vnrole='Source'/>
      <role fnrole='Path_end' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.4' fnframe='Cause_motion'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.5' fnframe='Bringing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Carrier' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='11.5' fnframe='Sending'> <!-- added -->
    <roles>
      <role fnrole='Sender' vnrole='' fnframe='Earnings_and_losses'/> <!-- added for Earnings_and_losses.earn.v -->
      <role fnrole='Earnings' vnrole='Theme'/>
      <role fnrole='Earner' vnrole='Agent'/>
      <!-- mapping for FE Buyer, VN role Source omitted because Buyer is non-core -->
    </roles>
  </vncls>
  <vncls class='13.2' fnframe='Giving'>
    <roles>
      <role fnrole='Donor' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.2' fnframe='Offering'>
    <roles>
      <role fnrole='Offerer' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Potential_recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.2' fnframe='Dispersal'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Individuals' vnrole='Theme'/>
      <role fnrole='Goal_area' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.2' fnframe='Commerce_pay'>
    <roles>
      <role fnrole='Buyer' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Seller' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.3' fnframe='Giving'>
    <roles>
      <role fnrole='Donor' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.3' fnframe='Offering'>
    <roles>
      <role fnrole='Offerer' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Potential_recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.3' fnframe='Surrendering_possession'>
    <roles>
      <role fnrole='Surrenderer' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.4' fnframe='Supply'>
    <roles>
      <role fnrole='Supplier' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Recipient' vnrole='Recipient'/>
    </roles>
  </vncls>
  <vncls class='13.5.1' fnframe='Communication_means'>
    <roles>
      <role fnrole='Communicator' vnrole='Agent'/>
      <role fnrole='Message' vnrole='Theme'/>
      <role fnrole='Topic' vnrole='Theme'/>
      <role fnrole='Addressee' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Commerce_buy'>
    <roles>
      <role fnrole='Buyer' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Commerce_collect'>
    <roles>
      <role fnrole='Buyer' vnrole='Agent'/>
      <role fnrole='Seller' vnrole='Source'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Money' vnrole='Asset'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Choosing'>
    <roles>
      <role fnrole='Cognizer' vnrole='Agent'/>
      <role fnrole='Chosen' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Getting'>
    <roles>
      <role fnrole='Recipient' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Receiving'>
    <roles>
      <role fnrole='Donor' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Taking'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='13.5.2' fnframe='Amassing'> <!-- added for Amassing.accumulate.v -->
    <roles>
      <role fnrole='Recipient' vnrole='Agent'/>
      <role fnrole='Mass_theme' vnrole='Theme'/>
        <!-- FN role Source, VN role theme not mapped because FE Source is non-core -->
    </roles>
  </vncls>
  <vncls class='13.5.3' fnframe='Hiring'>
    <roles>
      <role fnrole='Employer' vnrole='Agent'/>
      <role fnrole='Employee' vnrole='Theme'/>
      <role fnrole='Position' vnrole='Predicate'/> <!-- add VN role for Task -->
    </roles>
  </vncls>
  <vncls class='13.5.3' fnframe='Employing'>
    <roles>
      <role fnrole='Employer' vnrole='Agent'/>
      <role fnrole='Employee' vnrole='Theme'/>
      <role fnrole='Position' vnrole='Predicate'/> <!-- add VN role for Task -->
    </roles>
  </vncls>
  <vncls class='13.6' fnframe='Replacing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Old' vnrole='Theme'/> <!-- this seems wrong; and in fact the two words in the VN class can't even use the Theme role, which has to be plural: *She replaced the two shirts, in the sense of She switched the two shirts. -->
      <role fnrole='Old' vnrole='Theme1'/>
      <role fnrole='New' vnrole='Theme2'/>
      <role fnrole='Purpose' vnrole='Beneficiary'/>
      <role fnrole='Reason' vnrole='Beneficiary'/>
    </roles>
  </vncls>
  <vncls class='13.6' fnframe='Exchange'> <!-- added for Exchange.exchange.v -->
    <roles>
      <role fnrole='Exchanger_1' vnrole='Agent' />
      <role fnrole='Exchanger_2' vnrole='Recipient' />
      <role fnrole='Exchangers' vnrole='Agent' />
      <role fnrole='Theme_1' vnrole='Theme1' />
      <role fnrole='Theme_2' vnrole='Theme2' />
      <role fnrole='Themes' vnrole='Theme' />
    </roles>
  </vncls>
  <vncls class='13.6' fnframe='Take_place_of'> <!-- added for Take_place_of.substitute.v; not sure if this is right at all -->
    <roles>
      <role fnrole='New' vnrole='Theme2' />
      <role fnrole='Old' vnrole='Theme1' />
    </roles>
  </vncls>
  <vncls class='13.7' fnframe='Hunting'> <!-- added -->
    <roles>
      <role fnrole='Hunter' vnrole='Agent' />
    </roles>
  </vncls>
  <vncls class='14' fnframe='Getting'>
    <roles>
      <role fnrole='Recipient' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Topic'/>
      <role fnrole='Source' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='14' fnframe='Education_teaching'>
    <roles>
      <role fnrole='Student' vnrole='Agent'/>
      <role fnrole='Subject' vnrole='Topic'/>
      <role fnrole='Teacher' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='14' fnframe='Reading'>
    <roles>
      <role fnrole='Reader' vnrole='Agent'/>
      <role fnrole='Text' vnrole='Topic'/>
    </roles>
  </vncls>
  <vncls class='14-1' fnframe='Education_teaching'> <!-- added -->
    <roles>
      <role fnrole='Student' vnrole='Agent'/>
      <role fnrole='Subject' vnrole='Topic'/>
      <role fnrole='Teacher' vnrole='Source'/>
      <role fnrole='Material' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='14-2-1' fnframe='Education_teaching'> <!-- added -->
    <roles>
      <role fnrole='Student' vnrole='Agent'/>
      <role fnrole='Subject' vnrole='Topic'/>
      <role fnrole='Teacher' vnrole='Source'/>
      <role fnrole='Material' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='15.1' fnframe='Manipulation'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Entity' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='15.2' fnframe='Storing'> <!-- added for Storing.store.v -->
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Location' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='15.2' fnframe='Carry_goods'>
    <roles>
      <role fnrole='Distributor' vnrole='Agent'/>
      <role fnrole='Goods' vnrole='Theme'/>
      <role fnrole='Place' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='15.2' fnframe='Abandonment'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Depictive' vnrole='Location'/>
      <role fnrole='Place' vnrole='Location'/>
    </roles>
  </vncls>
  <vncls class='15.2' fnframe='Stinginess'>
    <roles>
      <role fnrole='Resource_controller' vnrole='Agent'/>
      <role fnrole='Resource' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='15.2' fnframe='Amassing'>
    <roles>
      <role fnrole='Recipient' vnrole='Agent'/>
      <role fnrole='Mass_theme' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='16' fnframe='Eclipse'>
    <roles>
      <role fnrole='Obstruction' vnrole='Agent'/>
      <role fnrole='Eclipsed' vnrole='Patient'/>
    </roles>
  </vncls>
  <vncls class='17.1' fnframe='Cause_impact'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Agent' vnrole='Cause'/>
      <role fnrole='Impactor' vnrole='Theme'/>
      <role fnrole='Impactee' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='17.1' fnframe='Cause_motion'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Cause'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='17.1' fnframe='Removing'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Cause'/>
      <role fnrole='Theme' vnrole='Theme'/>
      <role fnrole='Source' vnrole='Source'/>
      <role fnrole='Goal' vnrole='Destination'/>
    </roles>
  </vncls>
  <vncls class='17.1' fnframe='Shoot_projectiles'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Projectile' vnrole='Theme'/>
      <role fnrole='Firearm' vnrole='Source'/>
    </roles>
  </vncls>
  <vncls class='17.2' fnframe='Cause_harm'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Victim' vnrole='Theme'/>
      <role fnrole='Body_part' vnrole='Theme'/>
    </roles>
  </vncls>
  <vncls class='18.1' fnframe='Cause_harm'>
    <roles>
      <role fnrole='Agent' vnrole='Agent'/>
      <role fnrole='Cause' vnrole='Agent'/>
      <role fnrole='Victim' vnrole='Patient'/>